### ISSUE TITLE
Any releases?

### ISSUE THREAD

**Issue by ryanwinter** [Wintellect/SterlingDB#8]
Are there any planned nuget releases of this Sterling Fork?

**Comment by ushenkodmitry** [comment]
+1

**Comment by petermorlion** [comment]
Seeing as the last commit on this project is 3 years ago, I doubt it. You'd have to ask Jeremy or Wintellect, but I think they've moved on. I only helped by adding code so you could update/migrate databases, so I can't really speak for Wintellect (I'm not affiliated with them), but I suspect SterlingDB is currently in idle state...

**Comment by KeithJRome** [comment]
I don't believe that @JeremyLikness has any plans of that nature for Sterling.

**Comment by ryanwinter** [comment]
Thanks for the updates!

**Comment by vb2ae** [comment]
Take look at Lex.db it is very similar and still under development
